
package View;

import Model.DBStockSearch;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author SINGER
 */
public class BillingOption extends javax.swing.JFrame {

    /**
     * Creates new form BillingOption
     */
    public BillingOption() {
        initComponents();
        connect();
        //LoadProNo();
    }
    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    public void connect(){
                try {
            
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/product","root","");
            
        } catch (ClassNotFoundException ex) {
          
        } catch (SQLException ex) {
          
          

        
    }
    
   /* public void LoadProNo(){
        
        try {
            pst = conn.prepareStatement("SELECT id FROM product");
            rs = pst.executeQuery();
            idCMD.removeAllItems();
            while(rs.next())
            {
                
                idCMD.addItem(rs.getString(1));
                
            }
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(BillingOption.class.getName()).log(Level.SEVERE, null, ex);
        }*/        
        
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ltBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        proTB = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        qTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        nameTF1 = new javax.swing.JTextField();
        CategoryTF = new javax.swing.JTextField();
        clearTF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("Billing Option");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SINGER\\Pictures\\sup\\Capture2-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        ltBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        ltBtn.setForeground(new java.awt.Color(0, 153, 153));
        ltBtn.setText("LOGOUT");
        ltBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ltBtnActionPerformed(evt);
            }
        });
        jPanel3.add(ltBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 157, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 450));

        proTB.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        proTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRO_ID", "PRO_NAME", "Ctegory", "Quantity", "Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        proTB.setEditingColumn(2);
        proTB.setEditingRow(2);
        proTB.setRowHeight(20);
        jScrollPane1.setViewportView(proTB);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 480, 160));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Total :");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));
        jPanel1.add(totalTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 60, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Category");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, -1, -1));

        idTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTFKeyPressed(evt);
            }
        });
        jPanel2.add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 11, 80, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRO_ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRO_Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantity");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 14, -1, -1));

        qTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qTFActionPerformed(evt);
            }
        });
        jPanel2.add(qTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 11, 80, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 49, -1, -1));

        priceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTFActionPerformed(evt);
            }
        });
        jPanel2.add(priceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 49, 80, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Amount");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 80, -1, -1));

        amountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTFActionPerformed(evt);
            }
        });
        jPanel2.add(amountTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 77, 80, -1));

        addBTN.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        addBTN.setForeground(new java.awt.Color(0, 153, 153));
        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        jPanel2.add(addBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));
        jPanel2.add(nameTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 49, 80, -1));
        jPanel2.add(CategoryTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 80, 80, -1));

        clearTF.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        clearTF.setForeground(new java.awt.Color(0, 153, 153));
        clearTF.setText("CLEAR");
        clearTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTFActionPerformed(evt);
            }
        });
        jPanel2.add(clearTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 480, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ltBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ltBtnActionPerformed

        Login ln = new Login();
        ln.setVisible(true);

        super.dispose();
    }//GEN-LAST:event_ltBtnActionPerformed
    
    int sum=0;
    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        
        DefaultTableModel dtm = (DefaultTableModel)proTB.getModel();
        
        if(idTF.getText().length()==0){
            JOptionPane.showMessageDialog(null, " Please enter a product ", "Message ", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            dtm.addRow(new Object[]{
                idTF.getText(),
                nameTF1.getText(),
                CategoryTF.getText(),
                qTF.getText(),
                priceTF.getText(),
                amountTF.getText(),
            });
        }    
            sum=0;            
            for(int i=0;i<proTB.getRowCount();i++){
                sum = sum + Integer.parseInt(proTB.getValueAt(i, 5).toString());
            }
            totalTF.setText(Integer.toString(sum));
            
    }//GEN-LAST:event_addBTNActionPerformed

    private void idTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTFKeyPressed
        // TODO add your handling code here:
        ResultSet rs = new DBStockSearch().searchItem(idTF.getText());
        
        try {
            if(rs.next()==false){
                JOptionPane.showMessageDialog(null, "Product not found ", "Message ", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                nameTF1.setText(rs.getString("pname"));
                CategoryTF.setText(rs.getString("pcat"));
                qTF.setText(rs.getString("pquantity"));
                priceTF.setText(rs.getString("pprice"));
                int price = Integer.parseInt(rs.getString("pquantity"))*Integer.parseInt(rs.getString("pprice"));
                int tot = Integer.parseInt(rs.getString("pquantity"))*Integer.parseInt(rs.getString("pprice"));
                amountTF.setText(String.valueOf(tot));
                amountTF.setText(String.valueOf(price));

            
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillingOption.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_idTFKeyPressed

    private void clearTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTFActionPerformed

 idTF.setText(null);
 qTF.setText(null);
 nameTF1.setText(null);
 priceTF.setText(null);    
 CategoryTF.setText(null);
 amountTF.setText(null);
 

        // TODO add your handling code here:
    }//GEN-LAST:event_clearTFActionPerformed

    private void qTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qTFActionPerformed

    private void amountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTFActionPerformed
        try {
            // TODO add your handling code here:
            
            int amount = Integer.parseInt(rs.getString("pquantity"))*Integer.parseInt(rs.getString("pprice"));
        } catch (SQLException ex) {
            Logger.getLogger(BillingOption.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_amountTFActionPerformed

    private void priceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CategoryTF;
    private javax.swing.JButton addBTN;
    private javax.swing.JTextField amountTF;
    private javax.swing.JButton clearTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ltBtn;
    private javax.swing.JTextField nameTF1;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTable proTB;
    private javax.swing.JTextField qTF;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
