/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginController;
import java.util.logging.Level;
import java.util.logging.Logger;
import View.Home;

/**
 *
 * @author SINGER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        passTF = new javax.swing.JPasswordField();
        usName = new javax.swing.JButton();
        Clear_Btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 535));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("LOGIN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        username.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(0, 153, 153));
        username.setText("USER ID");
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        idTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });
        jPanel2.add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 90, -1));

        pass.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 153, 153));
        pass.setText("PASSWORD");
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, 31));

        passTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passTFKeyPressed(evt);
            }
        });
        jPanel2.add(passTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 90, -1));

        usName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usName.setForeground(new java.awt.Color(51, 51, 51));
        usName.setText("LOGIN");
        usName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usNameMouseClicked(evt);
            }
        });
        usName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usNameActionPerformed(evt);
            }
        });
        jPanel2.add(usName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        Clear_Btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Clear_Btn.setForeground(new java.awt.Color(51, 51, 51));
        Clear_Btn.setText("CLEAR");
        Clear_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_BtnActionPerformed(evt);
            }
        });
        jPanel2.add(Clear_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\SINGER\\Pictures\\sup\\Capture6-removebg-preview.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 70, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 460, 360));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\SINGER\\Pictures\\sup\\sup1.PNG")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 860, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 800, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void usNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usNameMouseClicked

String Userid=idTF.getText();
String Password=passTF.getText();
if(Userid.contains("seller")&& Password.contains("4321")){
    
    idTF.setText("");
    passTF.setText("");
    SellerP sp=new SellerP();
    sp.setVisible(true);
    
    super.dispose();
    
}
else{
    System.out.println("Something worng");
}

        
    }//GEN-LAST:event_usNameMouseClicked

    private void usNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usNameActionPerformed

String Userid=idTF.getText();
String Password=passTF.getText();
if(Userid.contains("admin")&& Password.contains("1234")){
    
    idTF.setText("");
    passTF.setText("");
    Home ob=new Home();
    ob.setVisible(true);
    
    super.dispose();
    
}
else{
    System.out.println("Something worng");
}
        
    }//GEN-LAST:event_usNameActionPerformed

    private void Clear_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_BtnActionPerformed
        // TODO add your handling code here:

        idTF.setText(null);
        passTF.setText(null);
        
    }//GEN-LAST:event_Clear_BtnActionPerformed

    private void passTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTFKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear_Btn;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JButton usName;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
