/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DBStockSearch;
import Model.DbConnection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asd
 */
public class StockManage extends javax.swing.JFrame {

    /**
     * Creates new form StockManage
     */
    public StockManage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ltBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        catCMB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        qTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        editBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        proTB = new javax.swing.JTable();
        nameTF = new javax.swing.JTextField();
        displayBTN = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("Manage Stock Panel");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 21, -1, -1));

        ltBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        ltBtn.setForeground(new java.awt.Color(0, 153, 153));
        ltBtn.setText("LOGOUT");
        ltBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ltBtnActionPerformed(evt);
            }
        });
        jPanel3.add(ltBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 331, 157, -1));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, -1, -1));

        backBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 153, 153));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel3.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 157, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\SINGER\\Pictures\\sup\\Capture0-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, 450));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText(" WELCOME TO STOCK PANEL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 11, 390, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 21, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRO_ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 93, -1, -1));
        jPanel1.add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 90, 88, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 131, -1, -1));
        jPanel1.add(priceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 128, 88, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRO_Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 131, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Category");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 174, -1, -1));

        catCMB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        catCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vagitables", " Fruits", "Sweets", "Foods" }));
        jPanel1.add(catCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 171, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 93, -1, -1));

        qTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qTFActionPerformed(evt);
            }
        });
        jPanel1.add(qTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 90, 88, -1));

        addBTN.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        addBTN.setForeground(new java.awt.Color(0, 153, 153));
        addBTN.setText("ADD");
        addBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBTNMouseClicked(evt);
            }
        });
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        jPanel1.add(addBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 218, -1, -1));

        editBTN.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        editBTN.setForeground(new java.awt.Color(0, 153, 153));
        editBTN.setText("EDIT");
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });
        jPanel1.add(editBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 218, -1, -1));

        deleteBTN.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        deleteBTN.setForeground(new java.awt.Color(0, 153, 153));
        deleteBTN.setText("DELETE");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 218, -1, -1));

        clearBTN.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        clearBTN.setForeground(new java.awt.Color(0, 153, 153));
        clearBTN.setText("CLEAR");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });
        jPanel1.add(clearBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 218, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("PRODUCTS LIST");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        proTB.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        proTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PRO_ID", "PRO_NAME", "Ctegory", "Quantity", "Price"
            }
        ));
        proTB.setEditingColumn(2);
        proTB.setEditingRow(2);
        proTB.setRowHeight(20);
        proTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(proTB);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 480, 160));
        jPanel1.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 90, 30));

        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });
        jPanel1.add(displayBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ltBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ltBtnActionPerformed

        Login ln = new Login();
        ln.setVisible(true);

        super.dispose();

    }//GEN-LAST:event_ltBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        Home h = new Home();
        h.setVisible(true);

        super.dispose();

    }//GEN-LAST:event_backBtnActionPerformed

    private void qTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qTFActionPerformed

    private void addBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBTNMouseClicked

    }//GEN-LAST:event_addBTNMouseClicked

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed

      //ResultSet rs = new DBsearch().product(idTF).();
     // int Qty=rs.getInt("");
         
        
        String id = idTF.getText();
        String name= nameTF.getText();
        String cat=catCMB.getSelectedItem().toString();
        String qnt=qTF.getText();
        String price=priceTF.getText();

        Controller.ManageStockController.addstock(id, name, cat, qnt, price);

    }//GEN-LAST:event_addBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        ResultSet r = new DBStockSearch().searchStock();
        DefaultTableModel dtm = (DefaultTableModel)proTB.getModel();
        dtm.setRowCount(0);
        
        try{
            Vector v;
            while(r.next()){
                v=new Vector();
                v.add(r.getString("pid"));
                v.add(r.getString("pname"));
                v.add(r.getString("pcat"));
                v.add(r.getString("pquantity"));
                v.add(r.getString("pprice"));
                dtm.addRow(v);
            }    
            DbConnection.closeCon();
        
        }
        catch(Exception e){
            e.printStackTrace();
            
        }
            
        
    }//GEN-LAST:event_displayBTNActionPerformed

    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTNActionPerformed

    DefaultTableModel tblModel = (DefaultTableModel)proTB.getModel();
    
    if(proTB.getSelectedRowCount()==1){
        
        String id = idTF.getText();
        String name= nameTF.getText();
        String cat=catCMB.getSelectedItem().toString();
        String qnt=qTF.getText();
        String price=priceTF.getText();
        
        tblModel.setValueAt(id,proTB.getSelectedRow(),0);
        tblModel.setValueAt(name,proTB.getSelectedRow(),1);
        tblModel.setValueAt(cat,proTB.getSelectedRow(),2);
        tblModel.setValueAt(qnt,proTB.getSelectedRow(),3);
        tblModel.setValueAt(price,proTB.getSelectedRow(),4);
        
        JOptionPane.showMessageDialog(this, "Edit Successfully");
        
    }else{
         if(proTB.getRowCount()==0){
             JOptionPane.showMessageDialog(this, "Table Is Empty");
         }else{
             JOptionPane.showMessageDialog(this, "Plese Select Row For Edit");
         }
        
    }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_editBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        
        idTF.setText("");
        nameTF.setText("");
        qTF.setText("");
        priceTF.setText("");
        
            JOptionPane.showMessageDialog(this, "Clear Successfully");

        
        
    }//GEN-LAST:event_clearBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        
 DefaultTableModel tblModel = (DefaultTableModel)proTB.getModel();
 
 if(proTB.getSelectedRowCount()==1){
 
     tblModel.removeRow(proTB.getSelectedRow());
     
    JOptionPane.showMessageDialog(this, "Delete Successfully");

     
 }else{
     
     if(proTB.getRowCount()==0){
         JOptionPane.showMessageDialog(this, "Table Is Empty");
     }else{
         JOptionPane.showMessageDialog(this, "Plese Select Row For Delete");
         
     }
 }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void proTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proTBMouseClicked

DefaultTableModel tblModel = (DefaultTableModel)proTB.getModel();

String proid = tblModel.getValueAt(proTB.getSelectedRow(), 0).toString();
String proname = tblModel.getValueAt(proTB.getSelectedRow(), 1).toString();
String categroy = tblModel.getValueAt(proTB.getSelectedRow(), 2).toString();
String quantity = tblModel.getValueAt(proTB.getSelectedRow(), 3).toString();
String price = tblModel.getValueAt(proTB.getSelectedRow(), 4).toString();

idTF.setText(proid);
nameTF.setText(proname);
catCMB.getSelectedItem();
qTF.setText(quantity);
priceTF.setText(price);
        // TODO add your handling code here:
    }//GEN-LAST:event_proTBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> catCMB;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JButton editBTN;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton ltBtn;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTable proTB;
    private javax.swing.JTextField qTF;
    // End of variables declaration//GEN-END:variables
}
